### ISSUE TITLE
C++14 support

### ISSUE THREAD

**Issue by seanmiddleditch** [seanmiddleditch/nanofmt#15]
Add the ability to compile in C++14 mode.

This mostly just means replacing use of `if constexpr`, likely only in C++14 builds given the cost of SFINAE overloads.

**Comment by seanmiddleditch** [comment]
This will be severely complicated by the fact that the Dragonbox reference implementation requires C++17.

**Comment by jk-jeon** [comment]
FYI, there is a C++14 port: https://github.com/robhz786/dragonbox/tree/cxx14

**Comment by seanmiddleditch** [comment]
This is no longer something I'm interested in; the C++14 projects that motivated this are now using C++17 or newer.
